#!/bin/bash

# Store JSON key file contents in variable
json_key=$(cat <<EOF
{
  "type": "service_account",
  "project_id": "YOUR_PROJECT_ID",
  "private_key_id": "YOUR_PRIVATE_KEY_ID",
  "private_key": "YOUR_PRIVATE_KEY",
  "client_email": "YOUR_CLIENT_EMAIL",
  "client_id": "YOUR_CLIENT_ID",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "YOUR_CLIENT_X509_CERT_URL"
}
EOF
)

# Store JSON key in a temporary file
json_file=$(mktemp)
echo "$json_key" > "$json_file"

# Use gcloud command to access GCP resources
gcloud auth activate-service-account --key-file="$json_file"
gcloud compute instances list

# Remove temporary file
rm "$json_file"



