#!/bin/bash

# Set the email address and passphrase length
EMAIL_ADDRESS="user@example.com"
PASSPHRASE_LENGTH=32

# Generate a GPG keypair without prompting for input
gpg --batch --gen-key <<EOF
    Key-Type: RSA
    Key-Length: 4096
    Subkey-Type: RSA
    Subkey-Length: 4096
    Name-Real: Example User
    Name-Email: $EMAIL_ADDRESS
    Expire-Date: 0
    Passphrase: $(openssl rand -base64 $PASSPHRASE_LENGTH)
    %commit
EOF

# Retrieve the generated passphrase
passphrase=$(gpg --export-secret-keys --no-armor $EMAIL_ADDRESS | \
            gpg --no-default-keyring --secret-keyring /dev/stdin \
                --list-packets | \
            awk '/# off=/{a=1} /:symkey enc packet:/ {a=0} a' | \
            grep 'keyid' | cut -d' ' -f2)

# Store the passphrase in Google Cloud Secret Manager
echo $passphrase | gcloud secrets create gpg-passphrase --data-file=-
