#!/bin/bash

# Set project ID and dataset ID
PROJECT_ID="your-project-id"
DATASET_ID="your-dataset-id"

# Set path to file containing view definitions
VIEWS_FILE="path/to/views/file.sql"

# Set path to service account JSON key
SA_KEY_FILE="path/to/service/account/key.json"

# Set environment variable for authentication
export GOOGLE_APPLICATION_CREDENTIALS=$SA_KEY_FILE

# Loop through each line in the views file
while read view; do
  # Create view in BigQuery
  echo "Creating view: $view"
  bq --project_id=$PROJECT_ID mk \
    --use_legacy_sql=false \
    --view="$view" \
    $DATASET_ID.$(echo "$view" | awk -F' ' '{print $3}')
done < "$VIEWS_FILE"
